research_task:
  description: >
    Search for the latest and most relevant neuroscience discoveries in areas such as
    sleep, memory, emotions, or cognitive enhancement. Use primary research sources
    (PubMed, Nature Neuroscience, Neuron) and integrate insights from expert commentary
    (Huberman Lab, Lex Fridman, educational lectures) to explain findings in a clear,
    educational way.

  expected_output: >
    A structured and educational research summary that includes:
      - A concise description of a specific discovery or topic.
      - Explanation of mechanisms behind the finding.
      - Real-world implications for health, learning, or performance.
      - Clearly labeled sources and short citations.
  agent: researcher


summarize_task:
  description: >

    The summary should extract the key features from the researcher that can be passed on to the content generation agent. Focus on the key information
    and summarize what you can in order to create a concise report. 


  expected_output: >

   A concise summary containing:
   1. Factual information
   2. Hard data when applicable
   3. Interesting results or discoveries 


  agent: summarizer
  # Wiring note: `agent: summarizer` ensures this task is handled by the `summarizer` agent
  # The crew's Process.sequential behavior causes this task to run after `research_task`.
  context: [research_task]

reporting_task:
  description: >
    Review the neuroscience research summary from the researcher and create a detailed video generation prompt for an AI video generator.
    The video should feature a wizard goat character explaining the key neuroscience concepts in an engaging, educational way.
    Transform the research findings into a compelling narrative that the wizard goat will present.
    Focus on making complex neuroscience concepts accessible and entertaining while maintaining scientific accuracy.
    Create specific visual descriptions, dialogue, and scene directions for the AI video generator.
  expected_output: >
    A comprehensive AI video generation prompt containing:
    1. Character description: Detailed description of the wizard goat (appearance, personality, mannerisms)
    2. Scene setting: Visual environment and background descriptions
    3. Script/Dialogue: What the wizard goat says to explain the neuroscience concepts
    4. Visual cues: Specific visual elements, animations, or graphics to accompany explanations
    5. Pacing and transitions: How the video flows between different concepts
    6. Educational hooks: Engaging ways to present metabolic health, hormone regulation, and brain optimization
    7. Call-to-action: How the wizard goat concludes and encourages viewers
    Format as a detailed video generation prompt ready for AI video creation tools.
  agent: content_creator
  context: [research_task]


video_generation_task:
  description: "Generate a video from the report.md script using Google Veo 3."
  expected_output: "An MP4 video file created by Veo."
  agent: "video_generator"
  inputs:
    script_file: "report.md"

