research_task:
  description: >
    Search the web for interesting and cutting-edge neuroscience topics, and then decide stick with a single topic. 
    
    Focus on finding the most scientifically-backed information from reputable sources.
    Create a concise but detailed research summary based on your web search findings.

  expected_output: >
    A focused research summary containing:
    A concise report but scientifically accurate and cite sources when possible.
    Facts are the most important aspect of your research
  agent: researcher


summarize_task:
  description: >

    The summary should extract the key features from the researcher that can be passed on to the content generation agent. Focus on the key information
    and summarize what you can in order to create a concise report. 


  expected_output: >

   A concise summary containing:
   1. Factual information
   2. Hard data when applicable
   3. Interesting results or discoveries 


  agent: summarizer
  # Wiring note: `agent: summarizer` ensures this task is handled by the `summarizer` agent
  # The crew's Process.sequential behavior causes this task to run after `research_task`.
  context: [research_task]

reporting_task:
  description: >
    Review the neuroscience research summary from the researcher and create a detailed video generation prompt for an AI video generator.
    The video should feature a wizard goat character explaining the key neuroscience concepts in an engaging, educational way.
    Transform the research findings into a compelling narrative that the wizard goat will present.
    Focus on making complex neuroscience concepts accessible and entertaining while maintaining scientific accuracy.
    Create specific visual descriptions, dialogue, and scene directions for the AI video generator.
  expected_output: >
    A comprehensive AI video generation prompt containing:
    1. Character description: Detailed description of the wizard goat (appearance, personality, mannerisms)
    2. Scene setting: Visual environment and background descriptions
    3. Script/Dialogue: What the wizard goat says to explain the neuroscience concepts
    4. Visual cues: Specific visual elements, animations, or graphics to accompany explanations
    5. Pacing and transitions: How the video flows between different concepts
    6. Educational hooks: Engaging ways to present metabolic health, hormone regulation, and brain optimization
    7. Call-to-action: How the wizard goat concludes and encourages viewers
    Format as a detailed video generation prompt ready for AI video creation tools.
  agent: content_creator
  context: [research_task]
